// Generated by scripts/generate-corpus-index.js. Do not edit.
// Run `npm run corpus:index` after adding or removing an example schema.

import s_asf_array from '../../demo/assets/example-schemas/asf-array.json';
import s_asf_basic_json_schema_type from '../../demo/assets/example-schemas/asf-basic-json-schema-type.json';
import s_asf_bootstrap_grid from '../../demo/assets/example-schemas/asf-bootstrap-grid.json';
import s_asf_complex_key_support from '../../demo/assets/example-schemas/asf-complex-key-support.json';
import s_asf_hack_conditional_required from '../../demo/assets/example-schemas/asf-hack-conditional-required.json';
import s_asf_kitchen_sink from '../../demo/assets/example-schemas/asf-kitchen-sink.json';
import s_asf_simple from '../../demo/assets/example-schemas/asf-simple.json';
import s_asf_tab_array from '../../demo/assets/example-schemas/asf-tab-array.json';
import s_asf_titlemap_examples from '../../demo/assets/example-schemas/asf-titlemap-examples.json';
import s_jsf_factory_sleek from '../../demo/assets/example-schemas/jsf-factory-sleek.json';
import s_jsf_fields_ace from '../../demo/assets/example-schemas/jsf-fields-ace.json';
import s_jsf_fields_actions from '../../demo/assets/example-schemas/jsf-fields-actions.json';
import s_jsf_fields_advancedfieldset from '../../demo/assets/example-schemas/jsf-fields-advancedfieldset.json';
import s_jsf_fields_array_simple from '../../demo/assets/example-schemas/jsf-fields-array-simple.json';
import s_jsf_fields_array from '../../demo/assets/example-schemas/jsf-fields-array.json';
import s_jsf_fields_authfieldset from '../../demo/assets/example-schemas/jsf-fields-authfieldset.json';
import s_jsf_fields_autocomplete from '../../demo/assets/example-schemas/jsf-fields-autocomplete.json';
import s_jsf_fields_checkbox from '../../demo/assets/example-schemas/jsf-fields-checkbox.json';
import s_jsf_fields_checkboxbuttons from '../../demo/assets/example-schemas/jsf-fields-checkboxbuttons.json';
import s_jsf_fields_checkboxes from '../../demo/assets/example-schemas/jsf-fields-checkboxes.json';
import s_jsf_fields_color from '../../demo/assets/example-schemas/jsf-fields-color.json';
import s_jsf_fields_common from '../../demo/assets/example-schemas/jsf-fields-common.json';
import s_jsf_fields_fieldset from '../../demo/assets/example-schemas/jsf-fields-fieldset.json';
import s_jsf_fields_help from '../../demo/assets/example-schemas/jsf-fields-help.json';
import s_jsf_fields_hidden from '../../demo/assets/example-schemas/jsf-fields-hidden.json';
import s_jsf_fields_iconselect from '../../demo/assets/example-schemas/jsf-fields-iconselect.json';
import s_jsf_fields_imageselect from '../../demo/assets/example-schemas/jsf-fields-imageselect.json';
import s_jsf_fields_password from '../../demo/assets/example-schemas/jsf-fields-password.json';
import s_jsf_fields_questions from '../../demo/assets/example-schemas/jsf-fields-questions.json';
import s_jsf_fields_radiobuttons from '../../demo/assets/example-schemas/jsf-fields-radiobuttons.json';
import s_jsf_fields_radios from '../../demo/assets/example-schemas/jsf-fields-radios.json';
import s_jsf_fields_range from '../../demo/assets/example-schemas/jsf-fields-range.json';
import s_jsf_fields_section from '../../demo/assets/example-schemas/jsf-fields-section.json';
import s_jsf_fields_select from '../../demo/assets/example-schemas/jsf-fields-select.json';
import s_jsf_fields_selectfieldset_key from '../../demo/assets/example-schemas/jsf-fields-selectfieldset-key.json';
import s_jsf_fields_selectfieldset from '../../demo/assets/example-schemas/jsf-fields-selectfieldset.json';
import s_jsf_fields_submit from '../../demo/assets/example-schemas/jsf-fields-submit.json';
import s_jsf_fields_tabarray_maxitems from '../../demo/assets/example-schemas/jsf-fields-tabarray-maxitems.json';
import s_jsf_fields_tabarray_value from '../../demo/assets/example-schemas/jsf-fields-tabarray-value.json';
import s_jsf_fields_tabarray from '../../demo/assets/example-schemas/jsf-fields-tabarray.json';
import s_jsf_fields_textarea from '../../demo/assets/example-schemas/jsf-fields-textarea.json';
import s_jsf_gettingstarted from '../../demo/assets/example-schemas/jsf-gettingstarted.json';
import s_jsf_previousvalues_multidimensional from '../../demo/assets/example-schemas/jsf-previousvalues-multidimensional.json';
import s_jsf_previousvalues from '../../demo/assets/example-schemas/jsf-previousvalues.json';
import s_jsf_schema_array from '../../demo/assets/example-schemas/jsf-schema-array.json';
import s_jsf_schema_basic from '../../demo/assets/example-schemas/jsf-schema-basic.json';
import s_jsf_schema_default from '../../demo/assets/example-schemas/jsf-schema-default.json';
import s_jsf_schema_inlineref from '../../demo/assets/example-schemas/jsf-schema-inlineref.json';
import s_jsf_schema_morecomplex from '../../demo/assets/example-schemas/jsf-schema-morecomplex.json';
import s_jsf_schema_required from '../../demo/assets/example-schemas/jsf-schema-required.json';
import s_jsf_templating_idx from '../../demo/assets/example-schemas/jsf-templating-idx.json';
import s_jsf_templating_tpldata from '../../demo/assets/example-schemas/jsf-templating-tpldata.json';
import s_jsf_templating_value from '../../demo/assets/example-schemas/jsf-templating-value.json';
import s_jsf_templating_values from '../../demo/assets/example-schemas/jsf-templating-values.json';
import s_json_schema_draft01 from '../../demo/assets/example-schemas/json-schema-draft01.json';
import s_json_schema_draft02 from '../../demo/assets/example-schemas/json-schema-draft02.json';
import s_json_schema_draft03 from '../../demo/assets/example-schemas/json-schema-draft03.json';
import s_json_schema_draft04 from '../../demo/assets/example-schemas/json-schema-draft04.json';
import s_json_schema_draft06 from '../../demo/assets/example-schemas/json-schema-draft06.json';
import s_ng_jsf_data_only from '../../demo/assets/example-schemas/ng-jsf-data-only.json';
import s_ng_jsf_deep_ref from '../../demo/assets/example-schemas/ng-jsf-deep-ref.json';
import s_ng_jsf_flex_layout from '../../demo/assets/example-schemas/ng-jsf-flex-layout.json';
import s_ng_jsf_layout_only from '../../demo/assets/example-schemas/ng-jsf-layout-only.json';
import s_ng_jsf_nested_arrays from '../../demo/assets/example-schemas/ng-jsf-nested-arrays.json';
import s_ng_jsf_select_list_examples from '../../demo/assets/example-schemas/ng-jsf-select-list-examples.json';
import s_ng_jsf_select_widget_examples from '../../demo/assets/example-schemas/ng-jsf-select-widget-examples.json';
import s_ng_jsf_simple_array from '../../demo/assets/example-schemas/ng-jsf-simple-array.json';
import s_rjsf_alternatives from '../../demo/assets/example-schemas/rjsf-alternatives.json';
import s_rjsf_arrays from '../../demo/assets/example-schemas/rjsf-arrays.json';
import s_rjsf_custom from '../../demo/assets/example-schemas/rjsf-custom.json';
import s_rjsf_date_and_time from '../../demo/assets/example-schemas/rjsf-date-and-time.json';
import s_rjsf_errors from '../../demo/assets/example-schemas/rjsf-errors.json';
import s_rjsf_files from '../../demo/assets/example-schemas/rjsf-files.json';
import s_rjsf_large from '../../demo/assets/example-schemas/rjsf-large.json';
import s_rjsf_nested from '../../demo/assets/example-schemas/rjsf-nested.json';
import s_rjsf_numbers from '../../demo/assets/example-schemas/rjsf-numbers.json';
import s_rjsf_ordering from '../../demo/assets/example-schemas/rjsf-ordering.json';
import s_rjsf_references from '../../demo/assets/example-schemas/rjsf-references.json';
import s_rjsf_simple from '../../demo/assets/example-schemas/rjsf-simple.json';
import s_rjsf_single from '../../demo/assets/example-schemas/rjsf-single.json';

/** Example schemas that are not valid JSON, so a bundler cannot import them. */
export const SKIPPED_NOT_JSON: string[] = [
  "jsf-events",
  "rjsf-custom-array",
  "rjsf-validation",
  "rjsf-widgets"
];

export const CORPUS: { name: string; form: any }[] = [
  { name: 'asf-array', form: s_asf_array },
  { name: 'asf-basic-json-schema-type', form: s_asf_basic_json_schema_type },
  { name: 'asf-bootstrap-grid', form: s_asf_bootstrap_grid },
  { name: 'asf-complex-key-support', form: s_asf_complex_key_support },
  { name: 'asf-hack-conditional-required', form: s_asf_hack_conditional_required },
  { name: 'asf-kitchen-sink', form: s_asf_kitchen_sink },
  { name: 'asf-simple', form: s_asf_simple },
  { name: 'asf-tab-array', form: s_asf_tab_array },
  { name: 'asf-titlemap-examples', form: s_asf_titlemap_examples },
  { name: 'jsf-factory-sleek', form: s_jsf_factory_sleek },
  { name: 'jsf-fields-ace', form: s_jsf_fields_ace },
  { name: 'jsf-fields-actions', form: s_jsf_fields_actions },
  { name: 'jsf-fields-advancedfieldset', form: s_jsf_fields_advancedfieldset },
  { name: 'jsf-fields-array-simple', form: s_jsf_fields_array_simple },
  { name: 'jsf-fields-array', form: s_jsf_fields_array },
  { name: 'jsf-fields-authfieldset', form: s_jsf_fields_authfieldset },
  { name: 'jsf-fields-autocomplete', form: s_jsf_fields_autocomplete },
  { name: 'jsf-fields-checkbox', form: s_jsf_fields_checkbox },
  { name: 'jsf-fields-checkboxbuttons', form: s_jsf_fields_checkboxbuttons },
  { name: 'jsf-fields-checkboxes', form: s_jsf_fields_checkboxes },
  { name: 'jsf-fields-color', form: s_jsf_fields_color },
  { name: 'jsf-fields-common', form: s_jsf_fields_common },
  { name: 'jsf-fields-fieldset', form: s_jsf_fields_fieldset },
  { name: 'jsf-fields-help', form: s_jsf_fields_help },
  { name: 'jsf-fields-hidden', form: s_jsf_fields_hidden },
  { name: 'jsf-fields-iconselect', form: s_jsf_fields_iconselect },
  { name: 'jsf-fields-imageselect', form: s_jsf_fields_imageselect },
  { name: 'jsf-fields-password', form: s_jsf_fields_password },
  { name: 'jsf-fields-questions', form: s_jsf_fields_questions },
  { name: 'jsf-fields-radiobuttons', form: s_jsf_fields_radiobuttons },
  { name: 'jsf-fields-radios', form: s_jsf_fields_radios },
  { name: 'jsf-fields-range', form: s_jsf_fields_range },
  { name: 'jsf-fields-section', form: s_jsf_fields_section },
  { name: 'jsf-fields-select', form: s_jsf_fields_select },
  { name: 'jsf-fields-selectfieldset-key', form: s_jsf_fields_selectfieldset_key },
  { name: 'jsf-fields-selectfieldset', form: s_jsf_fields_selectfieldset },
  { name: 'jsf-fields-submit', form: s_jsf_fields_submit },
  { name: 'jsf-fields-tabarray-maxitems', form: s_jsf_fields_tabarray_maxitems },
  { name: 'jsf-fields-tabarray-value', form: s_jsf_fields_tabarray_value },
  { name: 'jsf-fields-tabarray', form: s_jsf_fields_tabarray },
  { name: 'jsf-fields-textarea', form: s_jsf_fields_textarea },
  { name: 'jsf-gettingstarted', form: s_jsf_gettingstarted },
  { name: 'jsf-previousvalues-multidimensional', form: s_jsf_previousvalues_multidimensional },
  { name: 'jsf-previousvalues', form: s_jsf_previousvalues },
  { name: 'jsf-schema-array', form: s_jsf_schema_array },
  { name: 'jsf-schema-basic', form: s_jsf_schema_basic },
  { name: 'jsf-schema-default', form: s_jsf_schema_default },
  { name: 'jsf-schema-inlineref', form: s_jsf_schema_inlineref },
  { name: 'jsf-schema-morecomplex', form: s_jsf_schema_morecomplex },
  { name: 'jsf-schema-required', form: s_jsf_schema_required },
  { name: 'jsf-templating-idx', form: s_jsf_templating_idx },
  { name: 'jsf-templating-tpldata', form: s_jsf_templating_tpldata },
  { name: 'jsf-templating-value', form: s_jsf_templating_value },
  { name: 'jsf-templating-values', form: s_jsf_templating_values },
  { name: 'json-schema-draft01', form: s_json_schema_draft01 },
  { name: 'json-schema-draft02', form: s_json_schema_draft02 },
  { name: 'json-schema-draft03', form: s_json_schema_draft03 },
  { name: 'json-schema-draft04', form: s_json_schema_draft04 },
  { name: 'json-schema-draft06', form: s_json_schema_draft06 },
  { name: 'ng-jsf-data-only', form: s_ng_jsf_data_only },
  { name: 'ng-jsf-deep-ref', form: s_ng_jsf_deep_ref },
  { name: 'ng-jsf-flex-layout', form: s_ng_jsf_flex_layout },
  { name: 'ng-jsf-layout-only', form: s_ng_jsf_layout_only },
  { name: 'ng-jsf-nested-arrays', form: s_ng_jsf_nested_arrays },
  { name: 'ng-jsf-select-list-examples', form: s_ng_jsf_select_list_examples },
  { name: 'ng-jsf-select-widget-examples', form: s_ng_jsf_select_widget_examples },
  { name: 'ng-jsf-simple-array', form: s_ng_jsf_simple_array },
  { name: 'rjsf-alternatives', form: s_rjsf_alternatives },
  { name: 'rjsf-arrays', form: s_rjsf_arrays },
  { name: 'rjsf-custom', form: s_rjsf_custom },
  { name: 'rjsf-date-and-time', form: s_rjsf_date_and_time },
  { name: 'rjsf-errors', form: s_rjsf_errors },
  { name: 'rjsf-files', form: s_rjsf_files },
  { name: 'rjsf-large', form: s_rjsf_large },
  { name: 'rjsf-nested', form: s_rjsf_nested },
  { name: 'rjsf-numbers', form: s_rjsf_numbers },
  { name: 'rjsf-ordering', form: s_rjsf_ordering },
  { name: 'rjsf-references', form: s_rjsf_references },
  { name: 'rjsf-simple', form: s_rjsf_simple },
  { name: 'rjsf-single', form: s_rjsf_single },
];
