name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: setup Node
      uses: actions/setup-node@v7
      with:
        node-version-file: '.nvmrc'
    - run: npm ci
    - run: npm run build:demo

    - name: deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/demo
        exclude_assets: ''
